[global]
# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
showWarningOnDirectExecution = true

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "error"

[runner]
# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
magicEnabled = true

[server]
# List of folders that should not be watched for changes. Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
folderWatchBlacklist = ['']

# Allow files stored in static/ to be served
enableStaticServing = true

# If false, will attempt to open a browser window on start.
headless = true

# Automatically rerun script when the file is modified on disk.
runOnSave = false

# The port where the server will listen for client and browser connections.
port = 80

# Enables support for Cross-Origin Request Sharing, for added security.
enableCORS = true

[browser]
# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

[theme]
# The preset Streamlit theme that your custom theme inherits from.
base = "light"
